### ISSUE TITLE
Set all travisCI integrations to auto-build weekly

### ISSUE THREAD

**Issue by mossheim** [dn-m/Plan#9]

**Comment by mossheim** [comment]
Done:
- AirTurn
- AudioTools
- Color
- Dynamics
- Pitch
- ArithmeticTools
- EnsembleTools

**Comment by mossheim** [comment]
Also:
- plotmodel
- graphicstools
- staffview
- rhythmspellingtools
- staffmodel
- duration
- scoremodellayer
- musicxml
- graph
- scoreviewlayer
- osc

**Comment by mossheim** [comment]
* timeline
* path tools
* amm

done i think. i'll keep an eye to make sure nothing gets stale

**Comment by brianlheim** [comment]
* timeline
* path tools
* amm

done i think. i'll keep an eye to make sure nothing gets stale
